name: book_library
description: "Book Library"

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: any
  #outer service
  url_launcher: ^6.1.5
  #network service
  dio: ^4.0.6
  http: ^0.13.4
  #local path
  path_provider: ^2.1.2
  open_file: ^3.2.1
  #instance and locator
  get_it: any
  #network connectivity
  connectivity_plus: ^5.0.2
  #class different hashcode
  equatable: ^2.0.5
  #state management
  flutter_bloc: ^8.1.3
  #showcasing core concepts
  dartz: any
  #date/number formatting
  intl: ^0.19.0
  #book reader for Epub format
  epub_view: ^3.2.0
  #file downloader
  internet_file: ^1.2.0
  #cached image
  cached_network_image: ^3.3.0
  #local database
  #isar: ^3.1.0+1
  isar: ^4.0.0-dev.14
  #loading animation
  shimmer: ^3.0.0
  #isar_flutter_libs: ^3.1.0+1
  isar_flutter_libs: ^4.0.0-dev.14
  multi_select_flutter: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
 # isar_generator: ^3.1.0+1
  build_runner: ^2.4.9


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
