name: book_library
description: "Book Library"

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: any
  http: ^0.13.4
  url_launcher: ^6.1.5
  dio: ^4.0.6
  path_provider: ^2.0.11
  open_file: ^3.2.1
  #instance and locator
  get_it: any
  #network connectivity
  connectivity: any
  #class different hashcode
  equatable: ^2.0.5
  #state management
  flutter_bloc: ^8.1.3
  dartz: any
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
